### ISSUE TITLE
Add second batch

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/lincs-cell-painting#56] opened 2021-01-09 16:41 UTC
@shntnu - I remember you mentioning that we have another batch of Cell Painting data for this project. Can you point me to where this data lives?

We should work towards getting this data on here and processed. @sMyn42 is looking for a good dataset to test different batch effect correction tools (e.g. Harmony) to extend his Summer Research project. Having the second batch on here will help!

**Comment by shntnu** [comment] 2021-01-10 00:46
Duplicate of #57

**Closed by shntnu** 2021-01-10 00:46 UTC
